
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/favlist
    #    username: fav_admin
    username: postgres
    password: Aita1234

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect